apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-website
  labels:
    app: shopping-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-website
  template:
    metadata:
      labels:
        app: shopping-website
    spec:
      containers:
      - name: shopping-website
        image: ${{ vars.DOCKERHUB_USERNAME }}/dotnet:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10

