apiVersion: v1
kind: Service
metadata:
  name: shopping-website-service
  namespace: shopping
spec:
  selector:
    app: shopping-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
