apiVersion: v1
kind: Service
metadata:
  name: shopping-website-service
spec:
  selector:
    app: shopping-website
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
