apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-website
  namespace: shopping
  labels:
    app: shopping-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-website
  template:
    metadata:
      labels:
        app: shopping-website
    spec:
      tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: apps-auto-mode
      containers:
        - name: shopping-website
          image: ${IMAGE_URI}
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: dataprotection-keys
              mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
        - name: dataprotection-keys
          emptyDir: {}
