apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-website
  labels:
    app: shopping-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-website
  template:
    metadata:
      labels:
        app: shopping-website
    spec:
      tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: apps-auto-mode   
      containers:
      - name: shopping-website
        image: nikitaks997797/dotnet:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
<<<<<<< HEAD:k8s-deployment.yaml
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        volumeMounts:
        - name: dataprotection-keys
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: dataprotection-keys
        emptyDir: {}

=======
            cpu: "500m"
>>>>>>> 535fc471c1637c104daf4f43ca28f7e660116b57:k8s/k8s-deployment.yaml
