name: Deploy to k8s
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: set up kubeconfig
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBECONFIG }}"  > $HOME/.kube/config
            chmod 600 $HOME/.kube/config
      - name: deploy to k8s cluster
        run: |
          kubectl apply -f k8s/k8s-deployment.yaml
          kubectl apply -f k8s/k8s-service.yaml
          
      - name: verify deployment
        run: |
          kubectl get pods -n shopping
          kubectl get services -n shopping
          
