
# GitHub Actions workflow for .NET build and test
name: Deploy to EKS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          role-session-name: MySessionName
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}   
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/k8s-deployment.yaml
          kubectl apply -f k8s/k8s-service.yaml